server {
  listen 80;
    
  server_name brelkin.ru;
  return 301 $scheme://www.brelkin.ru$request_uri;

  location / {
    proxy_pass http://frontend:5173; 
  }  
  location /api {
    proxy_pass http://backend:1080;  
   }
}